SET SERVEROUTPUT ON;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE customer_rewards CASCADE CONSTRAINTS';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;
/

CREATE TABLE customer_rewards (
	reward_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	customer_email VARCHAR2(255) NOT NULL,
	gift_id        NUMBER NOT NULL,
	reward_date    DATE DEFAULT SYSDATE
);

ALTER TABLE customer_rewards
	ADD CONSTRAINT fk_customer_rewards_gift
	FOREIGN KEY (gift_id) REFERENCES gift_catalog(gift_id);

INSERT INTO customer_rewards (reward_id, customer_email, gift_id, reward_date)
VALUES (101, 'alice@example.com', 2, DATE '2025-11-12');

INSERT INTO customer_rewards (reward_id, customer_email, gift_id, reward_date)
VALUES (102, 'bob@example.org', 1, DATE '2025-11-12');

INSERT INTO customer_rewards (reward_id, customer_email, gift_id, reward_date)
VALUES (103, 'charlie@domain.com', 3, DATE '2025-11-12');

COMMIT;

SELECT * FROM customer_rewards;